- name: Create headscale folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - /docker/compose/headscale
    - /docker/volumes/headscale

- name: Copy headscale folder
  ansible.builtin.copy:
    src: ./docker/headscale/
    dest: /docker/compose/headscale/
    mode: "0644"

- name: Shutdown service
  ansible.builtin.shell: |
    cd /docker/compose/headscale
    docker compose down

- name: Start service
  ansible.builtin.shell: |
    cd /docker/compose/headscale
    docker compose up -d
